title: Yan LEI
logo: /assets/images/logo.avif
baseurl: 

##
# Collections configuration
##
collections:
  projects:
    output: true

##
# Contact Channels configuration
# Uncomment for enable. Available contact channels are email, github, telegram, stackoverflow, discord, mastodon.
# Please fell free to send a PR if you need a new one.
# DISABLE GITHUB setting it as an empty string: ""
# if false, then no contact channels will be display.
##
contact_channels_section: true
contact_channels:
  email: "yan.lei@u.nus.edu"
  # github: "https://github.com/a-chacon"
  # telegram: "https://t.me/"
  # stackoverflow: "https://stackoverflow.com"
  # discord: "https://discord.com/"
  # mastodon: "https://lile.cl/"
  # threads: "https://www.threads.net/@example"
  # linkedin: "https://www.linkedin.com/in/example/"

nav:
  - title: Home
    url: /
  - title: Curriculum Vitae
    url: /cv/
  - title: Research
    url: /research/
#  - title: Teaching
#    url: /teaching/
# - title: Contact
#    url: /contact/

cat_order:
  - title: Job Market Paper
    url: /research/jmp/
  - title: Publications
    url: /research/publication/
  - title: Working Papers
    url: /research/wp/

##
# Plugins configuration
##
plugins:
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-polyglot

##
# Polyglot configuration
##
languages: ["en"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true
